var gameview = {
  id: 22,
  created: 1525441591000,
  gameState: "BYPLACING",
  gamePlayers: [
    {
      id: 32,
      player: {
        id: 2,
        email: "berenguer.pou.llavina@gmail.com",
      },
      joinDate: 525441591000,
    },
    {
      id: 42,
      player: {
        id: 32,
        email: "mimi@gmail.com",
      },
      joinDate: 1525441625000,
    },
  ],
  ships: [
    {
      type: "carrier",
      locations: [],
    },
    {
      type: "battleship",
      locations: [],
    },
    {
      type: "submarine",
      locations: [],
    },
    {
      type: "destroyer",
      locations: [],
    },
    {
      type: "patrolboat",
      locations: [],
    },
  ],
  salvoes: [
    {
      turn: 1,
      player: 2,
      locations: ["J3", "J2", "J1"],
    },
    {
      turn: 2,
      player: 2,
      locations: ["H2", "H1", "I2"],
    },
    {
      turn: 3,
      player: 2,
      locations: ["G8", "C7", "G2"],
    },
    {
      turn: 4,
      player: 2,
      locations: ["F4", "F3", "F2"],
    },
    {
      turn: 1,
      player: 32,
      locations: ["A1", "B1", "A9"],
    },
    {
      turn: 2,
      player: 32,
      locations: ["D9", "E9", "F9"],
    },
    {
      turn: 3,
      player: 32,
      locations: ["G5", "F5"],
    },
    {
      turn: 4,
      player: 32,
      locations: ["J1", "J2", "J3"],
    },
  ],
  hits: {
    self: [
      {
        turn: 1,
        hitLocations: ["A1", "B1", "A10", "B10", "C10"],
        damages: {
          carrierHits: 0,
          battleshipits: 3,
          submarineits: 0,
          destroyerits: 0,
          patrolboatits: 2,
          carrier: 0,
          battleship: 3,
          submarine: 0,
          destroyer: 0,
          patrolboat: 2,
        },
        missed: 0,
      },
      {
        turn: 2,
        hitLocations: ["D10", "E10", "F10", "G10", "H10"],
        damages: {
          carrierHits: 0,
          battleshipHits: 1,
          submarineHits: 3,
          destroyerHits: 1,
          patrolboatHits: 0,
          carrier: 0,
          battleship: 4,
          submarine: 3,
          destroyer: 1,
          patrolboat: 2,
        },
        missed: 0,
      },
      {
        turn: 3,
        hitLocations: [],
        damages: {
          carrierHits: 0,
          battleshipHits: 0,
          submarineHits: 0,
          destroyerHits: 0,
          patrolboatHits: 0,
          carrier: 0,
          battleship: 4,
          submarine: 3,
          destroyer: 1,
          patrolboat: 2,
        },
        missed: 2,
      },
      {
        turn: 4,
        hitLocations: ["J1", "J2", "J3", "J4", "J5"],
        damages: {
          carrierHits: 5,
          battleshipHits: 0,
          submarineHits: 0,
          destroyerHits: 0,
          patrolboatHits: 0,
          carrier: 5,
          battleship: 4,
          submarine: 3,
          destroyer: 1,
          patrolboat: 2,
        },
        missed: 0,
      },
    ],
    opponent: [
      {
        turn: 1,
        hitLocations: ["J3", "J2", "J1", "J4", "J5"],
        damages: {
          carrierHits: 5,
          battleshipHits: 0,
          submarineHits: 0,
          destroyerHits: 0,
          patrolboatHits: 0,
          carrier: 5,
          battleship: 0,
          submarine: 0,
          destroyer: 0,
          patrolboat: 0,
        },
        missed: 0,
      },
      {
        turn: 2,
        hitLocations: ["H2", "H1", "I2", "I3", "I1"],
        damages: {
          carrierHits: 0,
          battleshipHits: 0,
          submarineHits: 3,
          destroyerHits: 0,
          patrolboatHits: 2,
          carrier: 5,
          battleship: 0,
          submarine: 3,
          destroyer: 0,
          patrolboat: 2,
        },
        missed: 0,
      },
      {
        turn: 3,
        hitLocations: ["G2", "G3", "G1"],
        damages: {
          carrierHits: 0,
          battleshipHits: 0,
          submarineHits: 0,
          destroyerHits: 3,
          patrolboatHits: 0,
          carrier: 5,
          battleship: 0,
          submarine: 3,
          destroyer: 3,
          patrolboat: 2,
        },
        missed: 2,
      },
      {
        turn: 4,
        hitLocations: ["F4", "F3", "F2", "F1"],
        damages: {
          carrierHits: 0,
          battleshipHits: 4,
          submarineHits: 0,
          destroyerHits: 0,
          patrolboatHits: 0,
          carrier: 5,
          battleship: 4,
          submarine: 3,
          destroyer: 3,
          patrolboat: 2,
        },
        missed: 1,
      },
    ],
  },
};
